Controllers/SeriesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Ticketr.Controllers
{
    public class SeriesController : Controller
    {
        // private readonly ILogger<EventController> _logger;

        private TicketrContext db;

        public SeriesController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("series/create")]
        public IActionResult CreateSeries()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User user = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            if(user.AccessLevel != "HeadAdmin" && user.AccessLevel != "GeneralAdmin")
            {
                return RedirectToAction("Dashboard", "Home");
            }
            List<Event> upcomingEvents = db.Events.Where(t => t.StartDate >= DateTime.Now).OrderBy(t => t.StartDate).ToList();
            ViewBag.UpcomingEvents = upcomingEvents;

            return View("NewSeries");
        }

        [HttpPost("series/create/new")]
        public IActionResult CreateNewSeries(Series newSeries)
        {
            List<Event> upcomingEvents = db.Events.Where(t => t.StartDate >= DateTime.Now).OrderBy(t => t.StartDate).ToList();
            ViewBag.UpcomingEvents = upcomingEvents;
            
            Series checkSeries = db.Series.FirstOrDefault(s => s.SeriesDate == newSeries.SeriesDate && s.SeriesTime == newSeries.SeriesTime && s.SeriesName == newSeries.SeriesName);
            if(checkSeries != null)
            {
                ModelState.AddModelError("RelatedEventCode", "This series already exists");
                return View("NewSeries");
            }
            Event checkEvent = db.Events.FirstOrDefault(e => e.EventCode == newSeries.RelatedEventCode);
            if(checkEvent == null)
            {
                ModelState.AddModelError("RelatedEventCode", "The code you typed does not exist");
                return View("NewSeries");
            }
            if(ModelState.ContainsKey("SeriesDate")== true)
            {
                ModelState["SeriesDate"].Errors.Clear();
            }
            if(newSeries.SeriesDate < checkEvent.StartDate)
            {
                ModelState.AddModelError("SeriesDate", "The series must happen on the day of or after the event beginning");
                return View("NewSeries");
            }
            if(newSeries.SeriesDate > checkEvent.EndDate)
            {
                ModelState.AddModelError("SeriesDate", "The series must happen on the day of or before the event ended");
                return View("NewSeries");
            }
            if(!ModelState.IsValid)
            {
                return View("NewSeries");
            }
            User curUser = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            newSeries.UserId = curUser.UserId;
            newSeries.EventId = checkEvent.EventId;
            newSeries.CombinedTime = new DateTime
            (
                newSeries.SeriesDate.Year,
                newSeries.SeriesDate.Month,
                newSeries.SeriesDate.Day,
                newSeries.SeriesTime.Hour,
                newSeries.SeriesTime.Minute,
                newSeries.SeriesTime.Second
            );

            db.Series.Add(newSeries);
            db.SaveChanges();

            return RedirectToAction("Details", "Event", new{EventId = newSeries.EventId});
        }

        [HttpGet("series/view/all")]
        public IActionResult ViewAllSeries()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User curUser = db.Users.FirstOrDefault(i => i.UserId == (int)uid);
            if(curUser.AccessLevel == "NewEmployee" )
            {
                return RedirectToAction("Dashboard","Home");
            }
            List<Series> allSeries = db.Series.Include(e => e.Event).OrderBy(t => t.CombinedTime).ToList();
            ViewBag.AllSeries = allSeries;

            return View("AllSeries");
        }

        [HttpGet("series/view/{SeriesId}")]
        public IActionResult SeriesDetails(int SeriesId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Series curSeries = db.Series.Include(e => e.Event).Include(p=> p.PatronsWatched).ThenInclude(p => p.Patron).FirstOrDefault(s => s.SeriesId == SeriesId);
            if(curSeries == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            List<SeriesSeatPatronRel> allAttending = db.SeriesSeatPatronRels
                .Include(p => p.Patron)
                .Include(ser => ser.Series)
                    .ThenInclude(serE => serE.Event)
                .Include(sea => sea.Seat)
                .Where(s => s.SeriesId == SeriesId)
                .OrderBy(seat => seat.Seat.SeatNumber)
                .ToList();
            
            ViewBag.AllAttending = allAttending;

            return View("SeriesDetails", curSeries);
        }

        [HttpGet("series/{SeriesId}/edit")]
        public IActionResult EditSeries(int SeriesId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Series curSeries = db.Series.Include(e => e.Event).FirstOrDefault(s => s.SeriesId == SeriesId);
            if(curSeries == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            List<Event> upcomingEvents = db.Events.Where(t => t.StartDate >= DateTime.Now).OrderBy(t => t.StartDate).ToList();
            ViewBag.UpcomingEvents = upcomingEvents;

            return View("EditSeries", curSeries);
        }

        [HttpPost("series/{SeriesId}/update")]
        public IActionResult UpdateSeries(int SeriesId, Series editSeries)
        {
            List<Event> upcomingEvents = db.Events.Where(t => t.StartDate >= DateTime.Now).OrderBy(t => t.StartDate).ToList();
            ViewBag.UpcomingEvents = upcomingEvents;
            
            Series curSeries = db.Series.FirstOrDefault(s => s.SeriesId == SeriesId);
            if(curSeries == null)
            {
                return RedirectToAction("ViewAllSeries");
            }
            Event checkEvent = db.Events.FirstOrDefault(e => e.EventCode == editSeries.RelatedEventCode);
            if(checkEvent == null)
            {
                ModelState.AddModelError("RelatedEventCode", "The code you typed does not exist");
                return View("EditSeries", curSeries);
            }
            if(ModelState.ContainsKey("SeriesDate")== true)
            {
                ModelState["SeriesDate"].Errors.Clear();
            }
            if(editSeries.SeriesDate < checkEvent.StartDate)
            {
                ModelState.AddModelError("SeriesDate", "The series must happen on the day of or after the event beginning");
                return View("EditSeries", curSeries);
            }
            if(editSeries.SeriesDate > checkEvent.EndDate)
            {
                ModelState.AddModelError("SeriesDate", "The series must happen on the day of or before the event ended");
                return View("EditSeries", curSeries);
            }
            if(!ModelState.IsValid)
            {
                return View("EditSeries", curSeries);
            }
            
            editSeries.CombinedTime = new DateTime
            (
                editSeries.SeriesDate.Year,
                editSeries.SeriesDate.Month,
                editSeries.SeriesDate.Day,
                editSeries.SeriesTime.Hour,
                editSeries.SeriesTime.Minute,
                editSeries.SeriesTime.Second
            );

            curSeries.SeriesName = editSeries.SeriesName;
            curSeries.SeriesDate = editSeries.SeriesDate;
            curSeries.SeriesTime = editSeries.SeriesTime;
            curSeries.CombinedTime = editSeries.CombinedTime;
            curSeries.SeriesVenue = editSeries.SeriesVenue;
            curSeries.TicketPrice = editSeries.TicketPrice;
            curSeries.TicketsAvailable = editSeries.TicketsAvailable;


            db.Series.Update(curSeries);
            db.SaveChanges();

            return RedirectToAction("SeriesDetails", new {SeriesId = SeriesId});
        }

        [HttpPost("series/{SeriesId}/delete")]
        public IActionResult DeleteSeries(int SeriesId)
        {
            Series curSeries = db.Series.FirstOrDefault(s => s.SeriesId == SeriesId);
            if(curSeries == null)
            {
                return RedirectToAction("ViewAllSeries");
            }

            db.Series.Remove(curSeries);
            db.SaveChanges();

Views/Series/AllSeries.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
        <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
        <h1>All Series</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Series Name</th>
                    <th scope="col">Event Name</th>
                    <th scope="col">Series Date & Time</th>
                    <th scope="col">Tickets Sold</th>
                    <th scope="col">Tickets Available</th>
                    <th scope="col">Base Price</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Net Sales</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.AllSeries)
                {
                    <tr>
                        <td><a asp-controller="Series" asp-action="SeriesDetails" asp-route-SeriesId="@item.SeriesId">@item.SeriesName</a></td>
                        <td>@item.Event.EventName</td>
                        <td>@item.CombinedTime.ToString("MM/dd/yyyy @ hh:mm tt")</td>
                        <td>@item.TicketsSold</td>
                        <td>@item.TicketsAvailable</td>
                        <td>$@Math.Round(item.BasePrice,2)</td>
                        <td>$@Math.Round(item.TotalDiscounts,2)</td>
                        <td>$@Math.Round(item.NetSales,2)</td>
                        <td><a asp-action="EditSeries" asp-controller="Series" asp-route-SeriesId="@item.SeriesId">Edit</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <button style="margin-left: 730px"><a asp-controller="Series" asp-action="CreateSeries">Create new Series</a></button>
        </div>
    </div>

</body>
</html>

Views/Series/EditSeries.cshtml
@model Series
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <p><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <form asp-action="DeleteSeries" asp-controller="Series" asp-route-SeriesId="@Model.SeriesId" style="margin-left: 650px" method="Post">
                    <input type="submit" value="Delete Series">
                </form>
            <h3>Edit this Series</h3>
            <form asp-action="UpdateSeries" asp-controller="Series" method="post" style="display: inline-block; margin-right: 100px; width: 200px;">
                <span asp-validation-for="RelatedEventCode"></span>
                </br>
                <label asp-for="RelatedEventCode"></label>
                <span>: </span>
                </br>
                <input asp-for="RelatedEventCode" value="@Model.Event.EventCode">
                </br>
                <span asp-validation-for="SeriesName"></span>
                </br>
                <label asp-for="SeriesName"></label>
                <span>: </span>
                </br>
                <input asp-for="SeriesName">
                </br>
                <span asp-validation-for="SeriesDate"></span>
                </br>
                <label asp-for="SeriesDate"></label>
                <span>: </span>
                </br>
                <input asp-for="SeriesDate">
                </br>
                <span asp-validation-for="SeriesTime"></span>
                </br>
                <label asp-for="SeriesTime"></label>
                <span>: </span>
                </br>
                <input asp-for="SeriesTime">
                </br>
                <span asp-validation-for="TicketsAvailable"></span>
                </br>
                <label asp-for="TicketsAvailable"></label>
                <span>: </span>
                </br>
                <input asp-for="TicketsAvailable">
                </br>
                <span asp-validation-for="SeriesVenue"></span>
                </br>
                <label asp-for="SeriesVenue"></label>
                <span>: </span>
                </br>
                <input asp-for="SeriesVenue">
                </br>
                <span asp-validation-for="TicketPrice"></span>
                </br>
                <label asp-for="TicketPrice"></label>
                <span>: </span>
                </br>
                <input asp-for="TicketPrice">
                </br>
                </br>
                <input type="submit" value="Update Event">
            </form>
            <table class="table" style="display: inline-block; vertical-align:top; width: 500px;">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Event Code</th>
                        <th scope="col">Starting Date</th>
                        <th scope="col">Event Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.UpcomingEvents)
                    {
                        <tr>
                            <td>@item.EventCode</td>
                            <td>@item.StartDate.ToString("MM/dd/yyyy")</td>
                            <td>@item.EventName</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</body>
</html>

Views/Series/NewSeries.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <partial name="_NewSeriesPartial"/>
            <table class="table" style="display: inline-block; vertical-align:top; width: 500px;">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Event Code</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Event Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.UpcomingEvents)
                    {
                        <tr>
                            <td>@item.EventCode</td>
                            <td>@item.StartDate.ToString("MM/dd/yyyy")</td>
                            <td>@item.EndDate.ToString("MM/dd/yyyy")</td>
                            <td>@item.EventName</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Views/Series/SeriesDetails.cshtml
@model Series
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <h1 style="text-align: center;">Details for @Model.SeriesName</h1>
            <p>Related Event: @Model.Event.EventName</p>
            <p>Series Date and Time: @Model.CombinedTime.ToString("MM/dd/yyyy @ hh:mm tt")</p>
            <p>Ticket Price: $@Math.Round(Model.TicketPrice,2)</p>
            <p>Tickets sold so far: @Model.TicketsSold</p>
            <p>Tickets Available: @Model.TicketsAvailable</p>
            <p>Base price: $@Math.Round(Model.BasePrice,2)</p>
            <p>Total discounts: $@Math.Round(Model.TotalDiscounts,2)</p>
            <p>Total Net Sales: $@Math.Round(Model.NetSales, 2)</p>
            <a asp-action="EditSeries" asp-controller="Series" asp-route-SeriesId="@Model.SeriesId">Edit</a>
            <p><button><a asp-controller="Patron" asp-action="ViewAllPatrons">Add Patrons to Series</a></button></p>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Patron Name</th>
                        <th scope="col">Price of ticket</th>
                        <th scope="col">Seat Number</th>
                        <th scope="col">View Details</th>
                        <th scope="col">Actions</th>                    
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.AllAttending)
                    {
                        <tr>
                            <td><a asp-action="PatronDetails" asp-controller="Patron" asp-route-PatronId="@item.Patron.PatronId">@item.Patron.FirstName @item.Patron.LastName</a></td>
                            <td>$@Math.Round(Model.TicketPrice,2)</td>
                            <td>@item.Seat.SeatNumber</td>
                            <td><a asp-controller="Patron" asp-action="PatronDetails" asp-route-PatronId="@item.PatronId">Patron Details</a></td>
                            <td><a asp-action="PrintTicket2" asp-controller="Patron" asp-route-PatronId="@item.PatronId" asp-route-SeriesId="@Model.SeriesId">Print Ticket</a></td>
                        </tr>
                    }
                </tbody>
                @* <tbody>
                    @foreach (var item in Model.PatronsWatched)
                    {
                        <tr>
                            <td>@item.Patron.FirstName @item.Patron.LastName</td>
                            <td>$@Math.Round(Model.TicketPrice,2)</td>
                            <td><a asp-controller="Patron" asp-action="PatronDetails" asp-route-PatronId="@item.PatronId">Patron Details</a></td>
                            <td><a asp-action="PrintTicket2" asp-controller="Patron" asp-route-PatronId="@item.PatronId" asp-route-SeriesId="@Model.SeriesId">Print Ticket</a></td>
                        </tr>
                    }
                </tbody> *@
            </table>
        </div>
    </div>

</body>
</html>

Views/Series/SeriesSearchResults.cshtml
@model List<Series>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <h1>Search results for "@ViewBag.SearchTerm"</h1>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Series Name</th>
                        <th scope="col">Event Name</th>
                        <th scope="col">Series Date & Time</th>
                        <th scope="col">Tickets Sold</th>
                        <th scope="col">Tickets Available</th>
                        <th scope="col">Base Price</th>
                        <th scope="col">Discount</th>
                        <th scope="col">Net Sales</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><a asp-controller="Series" asp-action="SeriesDetails" asp-route-SeriesId="@item.SeriesId">@item.SeriesName</a></td>
                            <td>@item.Event.EventName</td>
                            <td>@item.CombinedTime.ToString("MM/dd/yyyy @ hh:mm tt")</td>
                            <td>@item.TicketsSold</td>
                            <td>@item.TicketsAvailable</td>
                            <td>$@Math.Round(item.BasePrice,2)</td>
                            <td>$@Math.Round(item.TotalDiscounts,2)</td>
                            <td>$@Math.Round(item.NetSales,2)</td>
                            <td><a asp-action="EditSeries" asp-controller="Series" asp-route-SeriesId="@item.SeriesId">Edit</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Views/Series/_NewSeriesPartial.cshtml
@using Ticketr.Models;
@model Series;
<h3>Create a new Series</h3>
<form asp-action="CreateNewSeries" asp-controller="Series" method="post" style="display: inline-block; margin-right: 100px; width: 200px;">
    <span asp-validation-for="RelatedEventCode"></span>
    </br>
    <label asp-for="RelatedEventCode"></label>
    <span>: </span>
    </br>
    <input asp-for="RelatedEventCode">
    </br>
    <span asp-validation-for="SeriesName"></span>
    </br>
    <label asp-for="SeriesName"></label>
    <span>: </span>
    </br>
    <input asp-for="SeriesName">
    </br>
    <span asp-validation-for="SeriesDate"></span>
    </br>
    <label asp-for="SeriesDate"></label>
    <span>: </span>
    </br>
    <input asp-for="SeriesDate">
    </br>
    <span asp-validation-for="SeriesTime"></span>
    </br>
    <label asp-for="SeriesTime"></label>
    <span>: </span>
    </br>
    <input asp-for="SeriesTime">
    </br>
    <span asp-validation-for="TicketsAvailable"></span>
    </br>
    <label asp-for="TicketsAvailable"></label>
    <span>: </span>
    </br>
    <input asp-for="TicketsAvailable">
    </br>
    <span asp-validation-for="SeriesVenue"></span>
    </br>
    <label asp-for="SeriesVenue"></label>
    <span>: </span>
    </br>
    <input asp-for="SeriesVenue">
    </br>
    <span asp-validation-for="TicketPrice"></span>
    </br>
    <label asp-for="TicketPrice"></label>
    <span>: </span>
    </br>
    <input asp-for="TicketPrice">
    </br>
    </br>
    <input type="submit" value="Create Event">
</form>