Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Ticketr.Controllers
{
    public class EventController : Controller
    {
        // private readonly ILogger<EventController> _logger;

        private TicketrContext db;

        public EventController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("event/create")]
        public IActionResult Create()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User user = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            if(user.AccessLevel != "HeadAdmin")
            {
                return RedirectToAction("Dashboard", "Home");
            }

            return View("New");
        }

        [HttpPost("event/create/new")]
        public IActionResult CreateEvent(Event newEvent)
        {
            Event checkEvent = db.Events.FirstOrDefault(e => e.EventCode == newEvent.EventCode);
            if(checkEvent != null)
            {
                ModelState.AddModelError("EventCode", "This event code already exists");
            }
            if(ModelState.ContainsKey("StartDate") == true)
            {
                ModelState["StartDate"].Errors.Clear();
            }
            if(ModelState.ContainsKey("EndDate") == true)
            {
                ModelState["EndDate"].Errors.Clear();
            }
            if(newEvent.StartDate <= DateTime.Now)
            {
                ModelState.AddModelError("StartDate", "Starting Date must be a future date");
            }
            if(newEvent.EndDate <= DateTime.Now)
            {
                ModelState.AddModelError("EndDate", "Ending Date must be a future date");
            }
            long start = long.Parse(newEvent.StartDate.ToString("yyyyMMddHHmmss"));
            long end = long.Parse(newEvent.EndDate.ToString("yyyyMMddHHmmss"));
            if(end - start < 0)
            {
                ModelState.AddModelError("StartDate", "The show can't end before it begins");
            }
            if(!ModelState.IsValid)
            {
                return View("New");
            }
            User curUser = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            newEvent.UserId = curUser.UserId;

            db.Events.Add(newEvent);
            db.SaveChanges();

            return RedirectToAction("Details", new{EventId = newEvent.EventId});
        }

        [HttpGet("event/view/all")]
        public IActionResult ViewAll()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User curUser = db.Users.FirstOrDefault(i => i.UserId == (int)uid);
            if(curUser.AccessLevel != "HeadAdmin")
            {
                return RedirectToAction("Dashboard","Home");
            }
            List<Event> allEvents = db.Events.OrderBy(d => d.StartDate).ToList();
            // List<Event> allEvents = db.Events.Where(t => t.EndDate <= DateTime.Now).ToList();
            ViewBag.AllEvents = allEvents;

            return View("AllEvents");
        }

        [HttpGet("event/{EventId}/edit")]
        public IActionResult Edit(int EventId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Event curEvent = db.Events.FirstOrDefault(e => e.EventId == EventId);
            if(curEvent == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            return View("EditEvent", curEvent);
        }

        [HttpPost("event/{EventId}/update")]
        public IActionResult UpdateEvent(int EventId, Event editEvent)
        {
            Event curEvent = db.Events.FirstOrDefault(e => e.EventId == EventId);
            if(ModelState.ContainsKey("StartDate") == true)
            {
                ModelState["StartDate"].Errors.Clear();
            }
            if(ModelState.ContainsKey("EndDate") == true)
            {
                ModelState["EndDate"].Errors.Clear();
            }
            if(editEvent.StartDate <= DateTime.Now)
            {
                ModelState.AddModelError("StartDate", "Starting Date must be a future date");
            }
            if(editEvent.EndDate <= DateTime.Now)
            {
                ModelState.AddModelError("EndDate", "Ending Date must be a future date");
            }
            long start = long.Parse(editEvent.StartDate.ToString("yyyyMMddHHmmss"));
            long end = long.Parse(editEvent.EndDate.ToString("yyyyMMddHHmmss"));
            if(end - start < 0)
            {
                ModelState.AddModelError("StartDate", "The show can't end before it begins");
            }
            if(!ModelState.IsValid)
            {
                return View("Edit", editEvent);
            }

            curEvent.EventCode = editEvent.EventCode;
            curEvent.EventName = editEvent.EventName;
            curEvent.PriceMap = editEvent.PriceMap;
            curEvent.StartDate = editEvent.StartDate;
            curEvent.EndDate = editEvent.EndDate;
            curEvent.UpdatedAt = DateTime.Now;

            db.Events.Update(curEvent);
            db.SaveChanges();

            return RedirectToAction("Details", new{EventId = EventId});
        }

        [HttpGet("event/view/{EventId}")]
        public IActionResult Details(int EventId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Event curEvent = db.Events.Include(s => s.SeriesForEvent).FirstOrDefault(e => e.EventId == EventId);
            if(curEvent == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            List<Series> EventSeries = db.Series.Where(e => e.EventId == curEvent.EventId).OrderBy(rd => rd.CombinedTime).ToList();
            ViewBag.EventSeries = EventSeries;

            return View("Details", curEvent);
        }

        [HttpGet("event/search/")]
        public IActionResult SearchEvents(string SearchTerm)
        {
            List<Event> matchEvents = db.Events.Where(e => e.EventName.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase) || e.EventCode.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase)).ToList();
            ViewBag.SearchTerm = SearchTerm;
            return View("EventSearchResults", matchEvents);
        }
    }
}

Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Ticketr.Controllers
{
    public class PatronController : Controller
    {
        // private readonly ILogger<PatronController> _logger;

        private TicketrContext db;

        public PatronController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpGet("patron/create")]
        public IActionResult CreatePatron()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }

            return View("NewPatron");
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpPost("patron/create/new")]
        public IActionResult CreateNewPatron(Patron newPatron)
        {
            Patron checkPatron = db.Patrons.FirstOrDefault(p => p.FirstName == newPatron.FirstName && p.LastName == newPatron.LastName && p.PhoneNumber == newPatron.PhoneNumber && p.Address == newPatron.Address && p.DateOfBirth == newPatron.DateOfBirth);
            if(checkPatron != null)
            {
                ModelState.AddModelError("FirstName", "This patron is already in our database.");
            }
            if(ModelState.ContainsKey("DateOfBirth") == true)
            {
                ModelState["DateOfBirth"].Errors.Clear();
            }
            if(newPatron.DateOfBirth >= DateTime.Now)
            {
                ModelState.AddModelError("DateOfBirth", "Date of birth must be a past date");
            }
            if(!ModelState.IsValid)
            {
                return View("NewPatron");
            }

            if(newPatron.Email == null)
            {
                newPatron.Email = "None Given";
            }
            if(newPatron.FaxNumber == null)
            {
                newPatron.FaxNumber = "None Given";
            }
            if(newPatron.Website == null)
            {
                newPatron.Website = "None Given";
            }
            if(newPatron.SubscriptionModule == null)
            {
                newPatron.SubscriptionModule = "No Subscription";
            }

            User curUser = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            newPatron.UserId = curUser.UserId;

            db.Patrons.Add(newPatron);
            db.SaveChanges();
            return RedirectToAction("PatronDetails", new {PatronId = newPatron.PatronId});
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpGet("patron/view/all")]
        public IActionResult ViewAllPatrons()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }

            List<Patron> allPatrons = db.Patrons.OrderBy(i => i.PatronId).ToList();
            ViewBag.AllPatrons = allPatrons;

            return View("AllPatrons");
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpGet("patron/view/{PatronId}")]
        public IActionResult PatronDetails(int PatronId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }

            Patron curPatron = db.Patrons
                .Include(s => s.SeriesSeen)
                    .ThenInclude(ser => ser.Series)
                .Include(d => d.DonationsMade)
                .Include(t => t.TicketsPurchased)
                    .ThenInclude(s => s.Series)
                .FirstOrDefault(p => p.PatronId == PatronId);

            if(curPatron == null)
            {
                return RedirectToAction("Dashboard", "Home");
            }

            long dob = long.Parse(curPatron.DateOfBirth.ToString("yyyyMMdd"));
            long today = long.Parse(DateTime.Now.ToString("yyyyMMdd"));

            long age = today - dob;

            if(age < 180000)
            {
                ViewBag.PatronAge = age/10000;
                ViewBag.PatronStatus = "Youth";
            }
            else if(age > 650000)
            {
                ViewBag.PatronAge = age/10000;
                ViewBag.PatronStatus = "Senior";
            }
            else
            {
                ViewBag.PatronAge = age/10000;
                ViewBag.PatronStatus = "General Adult";
            }
            List<PatronSeriesRel> AllPatronSeries = db.PatronSeriesRels
                .Include(p => p.Patron)
                .Include(s => s.Series)
                    .ThenInclude(e => e.Event)
                .Where(pi => pi.PatronId == PatronId)
                .OrderBy(st => st.Series.CombinedTime)
                .ToList();
            ViewBag.AllPatronSeries = AllPatronSeries;

            decimal PatronTotalTickets = 0;
            foreach (var item in AllPatronSeries)
            {
                PatronTotalTickets += item.Series.TicketPrice;
            }
            ViewBag.PatronTotals = PatronTotalTickets;

            decimal totalDonations = 0;
            foreach(var item in curPatron.DonationsMade)
            {
                totalDonations += item.DonationAmount;
            }

            ViewBag.PatronDonations = totalDonations;

            List<SeriesSeatPatronRel> allSSPs = db.SeriesSeatPatronRels
                .Include(s => s.Series)
                    .ThenInclude(ps => ps.PatronsWatched)
                .Include(s => s.Series)
                    .ThenInclude(se => se.Event)
                .Include(p => p.Patron)
                .Include(s => s.Seat)
                .Where(p => p.PatronId == PatronId)
                .OrderBy(s => s.Series.CombinedTime)
                .ToList();

            ViewBag.AllSSPs = allSSPs;

            return View("PatronDetails", curPatron);
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpGet("patron/{PatronId}/edit")]
        public IActionResult EditPatron(int PatronId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Patron curPatron = db.Patrons.FirstOrDefault(p => p.PatronId == PatronId);
            if(curPatron == null)
            {
                return RedirectToAction("Dashboard","Home");
            }
            return View ("EditPatron", curPatron);
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpPost("patron/{PatronId}/update")]
        public IActionResult UpdatePatron(int PatronId, Patron editPatron)
        {
            Patron curPatron = db.Patrons.FirstOrDefault(p => p.PatronId == PatronId);
            if(curPatron == null)
            {
                return RedirectToAction("Dashboard", "Home");
            }
            if(ModelState.ContainsKey("DateOfBirth") == true)
            {
                ModelState["DateOfBirth"].Errors.Clear();
            }
            if(editPatron.DateOfBirth >= DateTime.Now)
            {
                ModelState.AddModelError("DateOfBirth", "Date of birth must be a past date");
            }
            if(!ModelState.IsValid)
            {
                return View("NewPatron");
            }

            curPatron.FirstName = editPatron.FirstName;
            curPatron.LastName = editPatron.LastName;
            curPatron.Address = editPatron.Address;
            curPatron.PhoneNumber = editPatron.PhoneNumber;
            curPatron.PhoneNumberType = editPatron.PhoneNumberType;
            curPatron.Email = editPatron.Email;
            curPatron.DateOfBirth = editPatron.DateOfBirth;
            curPatron.FaxNumber = editPatron.FaxNumber;
            curPatron.Website = editPatron.Website;
            curPatron.SubscriptionModule = editPatron.SubscriptionModule;
            curPatron.IsMilitary = editPatron.IsMilitary;
            curPatron.IsStudent = editPatron.IsStudent;
            curPatron.UpdatedAt = DateTime.Now;

            db.Patrons.Update(curPatron);
            db.SaveChanges();

            return RedirectToAction("PatronDetails", new {PatronId = PatronId});
        }
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpGet("patron/{PatronId}/PurchaseTicket")]

Views/Patron/AllPatrons.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <h1>All Patrons</h1>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Patron Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date of Birth</th>
                        <th scope="col">Address</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Email</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.AllPatrons)
                    {
                        <tr>
                            <td><a asp-controller="Patron" asp-action="PatronDetails" asp-route-PatronId="@item.PatronId">@item.PatronId</a></td>
                            <td><a asp-controller="Patron" asp-action="PatronDetails" asp-route-PatronId="@item.PatronId">@item.FirstName @item.LastName</a></td>
                            <td>@item.DateOfBirth.ToString("MM/dd/yy")</td>
                            <td>@item.Address</td>
                            <td>@item.PhoneNumber (@item.PhoneNumberType)</td>
                            <td>@item.Email</td>
                            <td><a asp-controller="Patron" asp-action="EditPatron" asp-route-PatronId="@item.PatronId">Edit</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <button style="margin-left: 730px"><a asp-controller="Patron" asp-action="CreatePatron">Create new Patron</a></button>
        </div>
    </div>
</body>
</html>

Views/Patron/EditPatron.cshtml
@model Patron
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <div>
                <h3>Edit patron details</h3>
                <form asp-controller="Patron" asp-action="UpdatePatron" method="Post" asp-route-PatronId="@Model.PatronId">
                    <span asp-validation-for="FirstName"></span>
                    </br>
                    <label asp-for="FirstName"></label>
                    <span>: (required)</span>
                    </br>
                    <input asp-for="FirstName">
                    </br>
                    <span asp-validation-for="LastName"></span>
                    </br>
                    <label asp-for="LastName"></label>
                    <span>: (required)</span>
                    </br>
                    <input asp-for="LastName">
                    </br>
                    <span asp-validation-for="Address"></span>
                    </br>
                    <label asp-for="Address"></label>
                    <span>: (required)</span>
                    </br>
                    <input asp-for="Address">
                    </br>
                    <span asp-validation-for="PhoneNumber"></span>
                    <span asp-validation-for="PhoneNumberType"></span>
                    </br>
                    <label asp-for="PhoneNumber"></label>
                    <span>: (required)</span>
                    </br>
                    <input asp-for="PhoneNumber">
                    <select asp-for="PhoneNumberType">
                        <option value="Home">Home</option>
                        <option value="Work">Work</option>
                        <option value="Cell">Cell</option>
                    </select>
                    </br>
                    <span asp-validation-for="DateOfBirth"></span>
                    </br>
                    <label asp-for="DateOfBirth"></label>
                    <span>: (required)</span>
                    </br>
                    <input asp-for="DateOfBirth">
                    </br>
                    <span asp-validation-for="Email"></span>
                    </br>
                    <label asp-for="Email"></label>
                    <span>: </span>
                    </br>
                    <input asp-for="Email">
                    </br>
                    <span asp-validation-for="FaxNumber"></span>
                    </br>
                    <label asp-for="FaxNumber"></label>
                    <span>: </span>
                    </br>
                    <input asp-for="FaxNumber">
                    </br>
                    <span asp-validation-for="Website"></span>
                    </br>
                    <label asp-for="Website"></label>
                    <span>: </span>
                    </br>
                    <input asp-for="Website">
                    </br>
                    <span asp-validation-for="SubscriptionModule"></span>
                    </br>
                    <label asp-for="SubscriptionModule"></label>
                    <span>: </span>
                    </br>
                    <input asp-for="SubscriptionModule">
                    </br>
                    <label asp-for="IsMilitary"></label>
                    <span>: </span>
                    <input asp-for="IsMilitary">
                    </br>
                    <label asp-for="IsStudent"></label>
                    <span>: </span>
                    <input asp-for="IsStudent">
                    </br>
                    <input type="submit" value="Edit Patron">
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Views/Patron/NewPatron.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <partial name="_NewPatronPartial" />
        </div>
    </div>
</body>
</html>

Views/Patron/PatronDetails.cshtml
@model Patron
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <h1 style="text-align: center;">Details for @Model.FirstName @Model.LastName</h1>
            <button style="margin-left: 297px;"><a asp-controller="Patron" asp-action="PurchaseTicket" asp-route-PatronId="@Model.PatronId">Purchase a ticket</a></button>
            <button><a asp-controller="Patron" asp-action="DonationPage" asp-route-PatronId="@Model.PatronId">Make a donation</a></button>
            <p></p>
            <p>Subscription Module: @Model.SubscriptionModule</p>
            <p>Date of Birth: @Model.DateOfBirth.ToString("MM/dd/yy")</p>
            <p>Age: @ViewBag.PatronAge</p>
            <p>Status: @ViewBag.PatronStatus</p>
            <p>Address: @Model.Address</p>
            <p>Phone Number: @Model.PhoneNumber (@Model.PhoneNumberType)</p>
            <p>Email: @Model.Email</p>
            <p>Fax Number: @Model.FaxNumber</p>
            <p>Website url: @Model.Website</p>
            @if(Model.IsMilitary == true)
            {
                <p>In the military: True</p>
            }
            else
            {
                <p>In the military: False</p>
            }
            @if(Model.IsStudent == true)
            {
                <p>Is a student: True</p>
            }
            else
            {
                <p>Is a student: False</p>
            }

            <p>Total in tickets purchased: $@Math.Round(ViewBag.PatronTotals,2)</p>
            <p>Total in donations: $@Math.Round(ViewBag.PatronDonations,2)</p>

            <p><a asp-controller="Patron" asp-action="editPatron" asp-route-PatronId="@Model.PatronId">edit</a></p>

            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date of purchase</th>
                        <th scope="col">Ticket Price</th>
                        <th scope="col">Ticket Seat</th>
                        <th scope="col">Name of show</th>
                        <th scope="col">Show for ticket</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.AllSSPs)
                    {
                        <tr>
                            @* <td>@item.Series.PatronsWatched.CreatedAt.ToString("MM/dd/yyyy @ hh:mm tt")</td> *@
                            <td>@item.CreatedAt.ToString("MM/dd/yyyy @ hh:mm tt")</td>
                            <td>$@Math.Round(item.Series.TicketPrice, 2)</td>
                            <td>@item.Seat.SeatNumber</td>
                            <td>@item.Series.Event.EventName</td>
                            <td>@item.Series.SeriesName</td>
                            <td><a asp-action="PrintTicket2" asp-controller="Patron" asp-route-PatronId="@Model.PatronId" asp-route-SeriesId="@item.SeriesId">Print Ticket</a></td>
                        </tr>
                    }
                </tbody>
                @* <tbody>
                    @foreach (var item in ViewBag.AllPatronSeries)
                    {
                        <tr>
                            <td>@item.CreatedAt.ToString("MM/dd/yyyy @ hh:mm tt")</td>
                            <td>$@Math.Round(item.Series.TicketPrice, 2)</td>
                            <td>@item.Series.Event.EventName</td>
                            <td>@item.Series.SeriesName</td>
                            <td><a asp-action="PrintTicket2" asp-controller="Patron" asp-route-PatronId="@Model.PatronId" asp-route-SeriesId="@item.SeriesId">Print Ticket</a></td>
                        </tr>
                    }
                </tbody> *@
            </table>
            
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        @* <th scope="col">Donation number</th> *@
                        <th scope="col">Date of donation</th>
                        <th scope="col">Donation amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.DonationsMade)
                    {
                        <tr>
                            @* <td>@item.DonationId</td> *@
                            <td>@item.CreatedAt.ToString("MM/dd/yyyy @ hh:mm tt")</td>
                            <td>$@Math.Round(item.DonationAmount, 2)</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</body>
</html>

Views/Patron/_NewDonationPartial.cshtml
@model Donation
@using Ticketr.Models
<form asp-action="MakeDonation" asp-controller="Patron" asp-route-PatronId="@Model.PatronId" method="Post">
    <span asp-validation-for="DonationAmount"></span>
    </br>
    <label asp-for="DonationAmount"></label>
    <span>: </span>
    <input asp-for="DonationAmount">
    <input type="submit" Value="Donate">
</form>