Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Ticketr.Controllers
{
    public class EventController : Controller
    {
        // private readonly ILogger<EventController> _logger;

        private TicketrContext db;

        public EventController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("event/create")]
        public IActionResult Create()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User user = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            if(user.AccessLevel != "HeadAdmin")
            {
                return RedirectToAction("Dashboard", "Home");
            }

            return View("New");
        }

        [HttpPost("event/create/new")]
        public IActionResult CreateEvent(Event newEvent)
        {
            Event checkEvent = db.Events.FirstOrDefault(e => e.EventCode == newEvent.EventCode);
            if(checkEvent != null)
            {
                ModelState.AddModelError("EventCode", "This event code already exists");
            }
            if(ModelState.ContainsKey("StartDate") == true)
            {
                ModelState["StartDate"].Errors.Clear();
            }
            if(ModelState.ContainsKey("EndDate") == true)
            {
                ModelState["EndDate"].Errors.Clear();
            }
            if(newEvent.StartDate <= DateTime.Now)
            {
                ModelState.AddModelError("StartDate", "Starting Date must be a future date");
            }
            if(newEvent.EndDate <= DateTime.Now)
            {
                ModelState.AddModelError("EndDate", "Ending Date must be a future date");
            }
            long start = long.Parse(newEvent.StartDate.ToString("yyyyMMddHHmmss"));
            long end = long.Parse(newEvent.EndDate.ToString("yyyyMMddHHmmss"));
            if(end - start < 0)
            {
                ModelState.AddModelError("StartDate", "The show can't end before it begins");
            }
            if(!ModelState.IsValid)
            {
                return View("New");
            }
            User curUser = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            newEvent.UserId = curUser.UserId;

            db.Events.Add(newEvent);
            db.SaveChanges();

            return RedirectToAction("Details", new{EventId = newEvent.EventId});
        }

        [HttpGet("event/view/all")]
        public IActionResult ViewAll()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            User curUser = db.Users.FirstOrDefault(i => i.UserId == (int)uid);
            if(curUser.AccessLevel != "HeadAdmin")
            {
                return RedirectToAction("Dashboard","Home");
            }
            List<Event> allEvents = db.Events.OrderBy(d => d.StartDate).ToList();
            // List<Event> allEvents = db.Events.Where(t => t.EndDate <= DateTime.Now).ToList();
            ViewBag.AllEvents = allEvents;

            return View("AllEvents");
        }

        [HttpGet("event/{EventId}/edit")]
        public IActionResult Edit(int EventId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Event curEvent = db.Events.FirstOrDefault(e => e.EventId == EventId);
            if(curEvent == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            return View("EditEvent", curEvent);
        }

        [HttpPost("event/{EventId}/update")]
        public IActionResult UpdateEvent(int EventId, Event editEvent)
        {
            Event curEvent = db.Events.FirstOrDefault(e => e.EventId == EventId);
            if(ModelState.ContainsKey("StartDate") == true)
            {
                ModelState["StartDate"].Errors.Clear();
            }
            if(ModelState.ContainsKey("EndDate") == true)
            {
                ModelState["EndDate"].Errors.Clear();
            }
            if(editEvent.StartDate <= DateTime.Now)
            {
                ModelState.AddModelError("StartDate", "Starting Date must be a future date");
            }
            if(editEvent.EndDate <= DateTime.Now)
            {
                ModelState.AddModelError("EndDate", "Ending Date must be a future date");
            }
            long start = long.Parse(editEvent.StartDate.ToString("yyyyMMddHHmmss"));
            long end = long.Parse(editEvent.EndDate.ToString("yyyyMMddHHmmss"));
            if(end - start < 0)
            {
                ModelState.AddModelError("StartDate", "The show can't end before it begins");
            }
            if(!ModelState.IsValid)
            {
                return View("Edit", editEvent);
            }

            curEvent.EventCode = editEvent.EventCode;
            curEvent.EventName = editEvent.EventName;
            curEvent.PriceMap = editEvent.PriceMap;
            curEvent.StartDate = editEvent.StartDate;
            curEvent.EndDate = editEvent.EndDate;
            curEvent.UpdatedAt = DateTime.Now;

            db.Events.Update(curEvent);
            db.SaveChanges();

            return RedirectToAction("Details", new{EventId = EventId});
        }

        [HttpGet("event/view/{EventId}")]
        public IActionResult Details(int EventId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            Event curEvent = db.Events.Include(s => s.SeriesForEvent).FirstOrDefault(e => e.EventId == EventId);
            if(curEvent == null)
            {
                return RedirectToAction("Dashboard","Home");
            }

            List<Series> EventSeries = db.Series.Where(e => e.EventId == curEvent.EventId).OrderBy(rd => rd.CombinedTime).ToList();
            ViewBag.EventSeries = EventSeries;

            return View("Details", curEvent);
        }

        [HttpGet("event/search/")]
        public IActionResult SearchEvents(string SearchTerm)
        {
            List<Event> matchEvents = db.Events.Where(e => e.EventName.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase) || e.EventCode.Contains(SearchTerm, StringComparison.OrdinalIgnoreCase)).ToList();
            ViewBag.SearchTerm = SearchTerm;
            return View("EventSearchResults", matchEvents);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;


namespace Ticketr.Controllers
{
    public class HomeController : Controller
    {
        // private readonly ILogger<HomeController> _logger;

        private TicketrContext db;

        public HomeController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            if(isLoggedIn == true)
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        [HttpGet("register")]
        public IActionResult Registration()
        {
            return View("Registration");
        }

        [HttpPost("registerAccount")]
        public IActionResult Register(User regUser)
        {
            if(ModelState.IsValid)
            {
                if(db.Users.Any(u => u.Email == regUser.Email))
                {
                    ModelState.AddModelError("Email", "Email already taken");
                }

                if(regUser.AccessLevel != "12345678" && regUser.AccessLevel != "abcdefgh" && regUser.AccessLevel != "87654321")
                {
                    //"12345678" == Head Manager == all access
                    //"87654321" == General Employee == cannot add events
                    //"abcdefgh" == New Employee == Can ONLY access patron pages. 
                    ModelState.AddModelError("AccessLevel", "The employer code you typed was incorrect. Please confirm you wrote the write code");
                }
            }
            
            if(ModelState.IsValid == false)
            {
                return View("Registration");
            }

            if(regUser.AccessLevel == "12345678")
            {
                regUser.AccessLevel = "HeadAdmin";
            }
            else if (regUser.AccessLevel == "87654321")
            {
                regUser.AccessLevel = "GeneralAdmin";
            }
            else
            {
                regUser.AccessLevel = "NewEmployee";
            }

            PasswordHasher<User> hasher = new PasswordHasher<User>();
            regUser.Password = hasher.HashPassword(regUser, regUser.Password);

            db.Users.Add(regUser);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost("loginAccount")]
        public IActionResult Login(LogUser logUser)
        {
            string errorMessage = "Email or Password was incorrect";
            
            if(ModelState.IsValid == false)
            {
                return View("Index");
            }
            
            User dbUser = db.Users.FirstOrDefault(u => u.Email == logUser.LoginEmail);
            if (dbUser == null)
            {
                ModelState.AddModelError("LoginEmail", errorMessage);
                return View("Index");
            }
            
            PasswordHasher<LogUser> hasher = new PasswordHasher<LogUser>();
            PasswordVerificationResult pwCompareResult = hasher.VerifyHashedPassword(logUser, dbUser.Password, logUser.LoginPassword);
            if (pwCompareResult == 0)
            {
                ModelState.AddModelError("LoginEmail", errorMessage);
                return View("Index");
            }

            HttpContext.Session.SetInt32("UserId", dbUser.UserId);
            HttpContext.Session.SetString("FullName", dbUser.FullName());

            return RedirectToAction("Dashboard");
        }

        [HttpGet("dashboard")]
        public IActionResult Dashboard()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }

            User curUser = db.Users.FirstOrDefault(u => u.UserId == (int)uid);
            ViewBag.CurrentUser = curUser;
            
            decimal totalTicketsPrice = 0;
            decimal totalDonations = 0;

            List<Event> allTickets = db.Events.Include(s => s.SeriesForEvent).ToList();
            List<Donation> allDonations = db.Donations.ToList();
            foreach(var item in allTickets)
            {
                foreach(var nextItem in item.SeriesForEvent)
                {
                    totalTicketsPrice += nextItem.NetSales;
                }
            }
            foreach (var item in allDonations)
            {
                totalDonations += item.DonationAmount;
            }
            
            ViewBag.TotalSales = totalTicketsPrice;
            ViewBag.TotalDonations = totalDonations;

            // var MyChart = new Chart(width: 200, height: 200)
            //     .AddTitle("Test")
            //     .AddSeries(chartType: "column",
            //         xValue: new[] {"A", "B", "C"},
            //         yValues: new[] {"1", "2","3"})
            //     .Write();

            ViewBag.TheatreLayout = "/Images/SeatingChartCrop.png";

            return View("Dashboard");
        }

        [HttpPost("logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SeatController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ticketr.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Ticketr.Controllers
{
    public class SeatController : Controller
    {
        private TicketrContext db;

        public SeatController(TicketrContext context)
        {
            db = context;
        }

        private int? uid
        {
            get
            {
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // HttpContext.Session.SetInt32("UserId", 1); //DELETE AFTERWARDS!!!!
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                // //////////////////////////////////////////////////////////////////
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("create/seat")]
        public IActionResult CreateSeat()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Dashboard", "Home");
            }

            List<Seat> allSeats = db.Seats.OrderByDescending(s => s.SeatId).ToList();
            ViewBag.Seats = allSeats;
            return View("NewSeat");
        }

        [HttpPost("create/new/seat")]
        public IActionResult NewSeat(Seat newSeat)
        {
            Seat curSeat = db.Seats.FirstOrDefault(s => s.SeatNumber == newSeat.SeatNumber);
            if(curSeat != null)
            {
                return View("NewSeat");
            }
            db.Seats.Add(newSeat);
            db.SaveChanges();
            return RedirectToAction("CreateSeat");
        }

        [HttpGet("seat/select/{PatronId}/{SeriesId}")]
        public IActionResult SelectSeat(int PatronId, int SeriesId)
        {
            List<Seat> RemainingSeats = db.Seats
                .Include(ssp => ssp.PatronInSeries)
                .Where(ssp => !ssp.PatronInSeries.Any(id => id.SeriesId == SeriesId))
                .ToList();
            ViewBag.TheatreLayout = "/Images/SeatingChartCrop.png";
            ViewBag.PatronId = PatronId;
            ViewBag.SeriesId = SeriesId;
            ViewBag.RemainingSeats = RemainingSeats;
            return View("SelectSeat");
        }

        [HttpPost("seat/choose/{PatronId}/{SeriesId}")]
        public IActionResult ChooseSeat(int PatronId, int SeriesId, SeriesSeatPatronRel newSeriesSeatPatronRel)
        {
            SeriesSeatPatronRel PatSeatShow = new SeriesSeatPatronRel
            {
                SeriesId = SeriesId,
                PatronId = PatronId,
                SeatId = newSeriesSeatPatronRel.SeatId
            };

            db.SeriesSeatPatronRels.Add(PatSeatShow);
            db.SaveChanges();

            return RedirectToAction("PurchaseTicket", "Patron", new {PatronId = PatronId});
        }
    }
}

Views/Home/Dashboard.cshtml
@* @model User *@
@{
    int? uid = @Context.Session.GetInt32("UserId");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <form asp-controller="Home" asp-action="Logout" method="Post">
                <p style="display: inline-block;"><a asp-controller="Home" asp-action="Dashboard">Dashboard</a> | <a asp-action="ViewAll" asp-controller="Event">View all events</a> | <a asp-action="ViewAllSeries" asp-controller="Series">View all Series</a> | <a asp-action="ViewAllPatrons" asp-controller="Patron">View all Patrons</a> </p>
                <input style="margin-left: 300px;" type="submit" value="logout">
            </form>
            <h3>This is the dashboard.</h3>
            <div style="width: 400px; display: inline-block;">
                @if(ViewBag.CurrentUser.AccessLevel == "HeadAdmin")
                {
                    <p>Patron Information</p>
                    <button><a asp-controller="Patron" asp-action="CreatePatron">Add a new Patron</a></button>
                    <button><a asp-controller="Patron" asp-action="ViewAllPatrons">See all Patrons</a></button>
                    <form asp-controller="Patron" asp-action="SearchPatrons" method="Get">
                        <label for="SearchTerm">Search Patrons:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                    <br>
                    <p>Event Information:</p>
                    <button><a asp-controller="Event" asp-action="Create">Create a new Event</a></button>
                    <button><a asp-controller="Event" asp-action="ViewAll">See all Events</a></button>
                    <form asp-controller="Event" asp-action="SearchEvents" method="Get">
                        <label for="SearchTerm">Search Event:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                    <br>
                    <p>Series Information</p>
                    <button><a asp-controller="Series" asp-action="CreateSeries">Create a new Series</a></button>
                    <button><a asp-controller="Series" asp-action="ViewAllSeries">See all Series</a></button>
                    <form asp-controller="Series" asp-action="SearchSeries" method="Get">
                        <label for="SearchTerm">Search Series:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                    <br>
                    <button><a asp-controller="Seat" asp-action="CreateSeat">Seat form cause I have to.</a></button>
                    
                    
                }
                else if(ViewBag.CurrentUser.AccessLevel == "GeneralAdmin")
                {
                    <p>Patron Information</p>
                    <button><a asp-controller="Patron" asp-action="CreatePatron">Add a new Patron</a></button>
                    <button><a asp-controller="Patron" asp-action="ViewAllPatrons">See all Patrons</a></button>
                    <form asp-controller="Patron" asp-action="SearchPatrons" method="Get">
                        <label for="SearchTerm">Search Patrons:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                    <br>
                    <p>Series Information</p>
                    <button><a asp-controller="Series" asp-action="CreateSeries">Create a new Series</a></button>
                    <button><a asp-controller="Series" asp-action="ViewAllSeries">See all Series</a></button>
                    <form asp-controller="Series" asp-action="SearchSeries" method="Get">
                        <label for="SearchTerm">Search Series:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                }
                else if (ViewBag.CurrentUser.AccessLevel == "NewEmployee")
                {
                    <p>Patron Information</p>
                    <button><a asp-controller="Patron" asp-action="CreatePatron">Add a new Patron</a></button>
                    <button><a asp-controller="Patron" asp-action="ViewAllPatrons">See all Patrons</a></button>
                    <form asp-controller="Patron" asp-action="SearchPatrons" method="Get">
                        <label for="SearchTerm">Search Patrons:</label>
                        <br>
                        <input name="SearchTerm" type="text">
                        <input type="submit" value="Search">
                    </form>
                }
            </div>
            <div style="width: 300px; display: inline-block; Vertical-Align:top;">
                <h3>Total Profits:</h3>
                <p>Total Ticket Income: $@Math.Round(ViewBag.TotalSales,2)</p>
                <p>Total Donation amount: $@Math.Round(ViewBag.TotalDonations,2)</p>
                <img src="@ViewBag.TheatreLayout" alt="Seating chart of CodingDojo Productions, Mainstage" style="width: 130%; height: auto; border: 3px solid black;">
            </div>

            @* <div>
                @{
                    var MyChart = new Chart(width: 200, height: 200)
                        .AddTitle("Test")
                        .AddSeries(chartType: "column",
                            xValue: new[] {"A", "B", "C"},
                            yValues: new[] {"1", "2","3"})
                        .Write();

                }
            </div> *@
            
        </div>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <h1 style="text-align: Center;">Ticket'R</h1>
            <partial name="_LoginPartial"/>
            </br>
            <p style="text-align: center;"><a asp-action="Registration" asp-controller="Home">Register?</a></p>
        </div>
    </div>
</body>
</html>

Views/Home/Registration.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="BackgroundWrapper">
        <div class="InnerWrapper">
            <partial name="_RegistrationPartial" />
        </div>
    </div>
</body>
</html>

Views/Home/_RegistrationPartial.cshtml
@using Ticketr.Models
@model User
<div class= "registration">
    <p style="text-align: right;"><a asp-controller="Home" asp-action="Index">Login</a></p>
    <h3 style="text-align: center;">Register</h3>
    <form asp-action="register" asp-controller="home" method="post">
        <span asp-validation-for="AccessLevel"></span>
        </br>
        <label asp-for="AccessLevel"></label>
        <span>: </span>
        </br>
        <input asp-for="AccessLevel">
        </br>
        <span asp-validation-for="FirstName"></span>
        </br>
        <label asp-for="FirstName"></label>
        <span>: </span>
        </br>
        <input asp-for="FirstName">
        </br>
        <span asp-validation-for="LastName"></span>
        </br>
        <label asp-for="LastName"></label>
        <span>: </span>
        </br>
        <input asp-for="LastName">
        </br>
        <span asp-validation-for="Email"></span>
        </br>
        <label asp-for="Email"></label>
        <span>: </span>
        </br>
        <input asp-for="Email">
        </br>
        <span asp-validation-for="Password"></span>
        </br>
        <label asp-for="Password"></label>
        <span>: </span>
        </br>
        <input asp-for="Password">
        </br>
        <span asp-validation-for="ConfirmPassword"></span>
        </br>
        <label asp-for="ConfirmPassword"></label>
        <span>: </span>
        </br>
        <input asp-for="ConfirmPassword">
        </br>
        </br>
        <input type="submit" value="Submit">
    </form>
</div>